language: php
php:
  - 5.3
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: 5.3 # works locally?
install:
  - composer update --prefer-source --no-interaction
script:
  - phpunit --coverage-text
